name = "StaticTools"
uuid = "86c06d3c-3f03-46de-9781-57580aa96d0a"
authors = ["C. Brenhin Keller and contributors"]
version = "0.4.3"

[deps]
ManualMemory = "d125e4d3-2237-4719-b19c-fa641b8a4667"

[compat]
julia = "1.7"
ManualMemory = "0.1.8"
